### ISSUE TITLE
gist功能

### ISSUE THREAD

**Issue by wineen** [scoful/cloudSkyMonster#12]
我在使用gist功能的时候，经常提示获取失败，也无法进入到获取token这一步，能否先允许配置token功能，然后再测试api是否能够正常使用，然后做同步功能这样呢，目前的情况无法确定gist功能是否可用，我token已经拿到了，没有配置入口。

**Comment by scoful** [comment]
可以这样操作，你先把你的东西导出来，然后删了插件，重新来，这个配置入口在第一次，有个弹窗的。目前还很粗糙，后面闲了需要重构一下。

**Comment by milo-wjh** [comment]
我也无法使用  第一次展开标签的时候 填了token     拉取推送的时候还会弹  填了也无效
重装过
