### ISSUE TITLE
希望上架到商店，这样多台电脑Chrome就能自动同步扩展。

### ISSUE THREAD

**Issue by iamvicliu** [scoful/cloudSkyMonster#18]
1、希望上架到商店，这样多台电脑Chrome就能自动同步扩展。
2、云同步功能，可以在扩展安装到本地后，再进行配置

**Comment by orrzz** [comment]
增加账号登录功能 实现云同步 +1

**Comment by scoful** [comment]
已上架，https://chrome.google.com/webstore/detail/cloudskymonster/niahhcandihcfbamcfhikgojghnnfjan
