### ISSUE TITLE
建议开发者将这个插件上传到chrome扩展商店，现在谷歌浏览器下载crx文件会自动删除，并且就是开发者模式加入也无法使用

### ISSUE THREAD

**Issue by sjhsbhqf** [scoful/cloudSkyMonster#21]
建议开发者将这个插件上传到chrome扩展商店，现在谷歌浏览器下载crx文件会自动删除，并且就是开发者模式加入也无法使用

![image](https://user-images.githubusercontent.com/41407099/200152762-63dd2725-5b77-4523-a06a-e167f4f687c4.png)

![image](https://user-images.githubusercontent.com/41407099/200152787-763f4c0a-754e-4e7c-9b05-dbf01c4b0068.png)

**Comment by ZhianLin** [comment]
改后缀名为.zip，解压出来后通过扩展管理的“加载已解压的扩展程序”来安装。

**Comment by scoful** [comment]
@sjhsbhqf @ZhianLin 已上架，地址：https://chrome.google.com/webstore/detail/cloudskymonster/niahhcandihcfbamcfhikgojghnnfjan
