### ISSUE TITLE
gist 推送问题，gistld没有保存。

### ISSUE THREAD

**Issue by taklele** [scoful/cloudSkyMonster#23]
配置好gist key之后，同步数据为空，查看日志看到一条：gistId没有保存，请问这是否是同步错误的关键？该如何解决？
```
自动推送到gitee
开始：2023-07-15 17:27:12
自动推送到gitee的gist
开始推送到gitee的gist的任务
开始检查gitee token有没有保存
gitee token有保存
开始检查gistId有没有保存
gistId没有保存
0秒等待
推送到gitee的gist的任务结束
结束：2023-07-15 17:27:13
```

**Comment by scoful** [comment]
解决了嘛？你可以试试手动推一次看看

**Comment by taklele** [comment]
> 解决了嘛？你可以试试手动推一次看看

没有解决，手动推好像没效果。
日志中看不到手动推的记录。

**Comment by scoful** [comment]
> 

1. 是不是没内容啊？先收藏几条记录
2. 这个功能是用来不同电脑同步的，如果没有这个需求，不配置也ok
3. 我刚试了一下，推成功后，右下角会弹窗的
4. 再一个去看看gitee里的代码片段，是不是有记录了
