### ISSUE TITLE
建议：类似onetab那样，点击网址后，网址自动消失在记录中，而不是还保存着

### ISSUE THREAD

**Issue by sjhsbhqf** [scoful/cloudSkyMonster#24]
建议：类似onetab那样，点击网址后，网址自动消失在记录中，而不是还保存着

**Comment by scoful** [comment]
支持配置的，在“其他功能-查看配置”里，可以配置是要保存还是删除
![image](https://github.com/scoful/cloudSkyMonster/assets/12808733/13e0f470-af9d-4679-80ac-4f826c9ddf48)
