### ISSUE TITLE
BUG：自动同步间隔时间

### ISSUE THREAD

**Issue by sjhsbhqf** [scoful/cloudSkyMonster#25]
，你在说明文档中说是90分钟保存一次，但是我在日志中看到的是90秒保存一次
![image](https://github.com/scoful/cloudSkyMonster/assets/41407099/fdd57c32-5292-4310-86cc-6d17b9401003)

**Comment by scoful** [comment]
sorry，才来翻issue，翻了一下代码，是90分钟，还有个触发条件，_“持续监听，假如锁屏或者睡眠就清空定时任务，激活再重新定时任务”_，可能这就是日志这样显示的原因
