### ISSUE TITLE
设置TOKEN的位置不明确

### ISSUE THREAD

**Issue by sjhsbhqf** [scoful/cloudSkyMonster#26]
设置TOKEN的位置不明确，比如我github的token三个月之后过期，我没办法找到设置token的地方，除非重装后，第一次设置token

**Comment by scoful** [comment]
sorry，才来翻issue，这个的确是问题，当初没考虑，列入todo

**Comment by sjhsbhqf** [comment]
这个版本，已经上传了吗

**Comment by scoful** [comment]
@sjhsbhqf 稍等

**Comment by sjhsbhqf** [comment]
感谢哥们，你国庆节还调代码哈哈哈哈哈哈

**Comment by scoful** [comment]
@sjhsbhqf 可以了，v2.0.4，哈哈，拖延症
