### ISSUE TITLE
你好，已经设置了gitee的gist还是无法恢复同步

### ISSUE THREAD

**Issue by dxmaimxd** [scoful/cloudSkyMonster#27]
你好，我已经按照教程配置了gitee的私钥，然后我先保存到gitee
然后我测试删除了一组收藏夹，再选择从gitee拉取回来，却无法恢复收藏页面

**Comment by scoful** [comment]
1. 你好，出现你这个情况是因为，同步是无感知的，当你删除了一整组的时候，其实已经触发了同步，把这个行为同步到gitee了，所以你再从gitee恢复，就相当于原样子了。（只限gitee，github不会自动同步，如果想测试这个功能，建议配置github的）
2. 其实页面那4个手动同步功能，据我这4年用下来，几乎是用不到的，除非你把插件移除了，重新配置私钥，重新手动从gitee上拉取下来。
3. 如果想测试的是误删了标签或者标签组，想恢复，这个可能需要一个类回收站功能，属于新增需求，还没实现。

**Comment by dxmaimxd** [comment]
> 3\. 还没

好的谢谢，我也主要是本地使用，这次onetab宕机才有幸找到您的项目，谢谢你的cloudskymonster让我备份数据
