### ISSUE TITLE
建议移除popup，单击插件图标直接打开workbrench

### ISSUE THREAD

**Issue by ciaranchen** [scoful/cloudSkyMonster#29]
popup现在的功能只是展示打开了的标签页，与浏览器本身的标签栏是重复的；相反更常用的展示所有已保存的标签页却需要 `右键 -> 功能菜单 -> 展示收集的标签` 三个步骤才能到达。所以建议将左键点击插件图标的功能设置为直接打开workbrench

**Comment by scoful** [comment]
good idea

**Comment by scoful** [comment]
你好，看到你的pr了，我也在修改ing，你这个需求也修改好了

**Comment by scoful** [comment]
@ciaranchen v3的也在进行中，因为要先fix已知的bug，所以要押后一点点

**Comment by ciaranchen** [comment]
作者好，就是我希望参与到这个项目的开发，我希望对代码进行一些重构，想问问你的意见，能否加一下你的微信？
