### ISSUE TITLE
[功能建议] 深色模式和商店上架问题

### ISSUE THREAD

**Issue by jiongjiongzj** [scoful/cloudSkyMonster#33]
还没开始深度使用就遇到了一些小问题：
1. 只能从github下载zip包，crx封装的文件会被chrome系浏览器直接删除。建议上一下商店，增加触及。
2. 没有深色模式...对于夜猫子来说纯白界面太痛苦了。苦于不会css，不然我就自己动手了。如果不方便更新的话，大佬能不能给一个简单的修改方案？直接改css文件的哪个位置能达到类似深色模式的效果？

**Comment by jiongjiongzj** [comment]
3. 能不能将数据默认保存在单个文件里，而非和其他插件保存在leveldb文件夹，方便用户自行选择同步工具？

**Comment by scoful** [comment]
1. 上架的事在整ing，Chrome的插件系统升级不向下兼容，编程界好喜欢整这种事，不向下兼容emmm
2. 深色模式是什么样的模式，能说一下你的整体深色模式方案吗？指的是你整个系统的深色模式？单独浏览器的深色模式？你喜欢的深色模式的样子(特指网页版)？因为本人所有开发工具都是白底黑字，get不到深色模式的美，最好能提供一下步骤或者截图，或者你喜欢的已经实现的网页的深色模式，学习一下
3. 数据单独存储，是Chrome自己卡死了权限，不能直接操作本地问题，没法搞的

**Comment by scoful** [comment]
@jiongjiongzj

**Comment by scoful** [comment]
@jiongjiongzj 已上架，地址：https://chrome.google.com/webstore/detail/cloudskymonster/niahhcandihcfbamcfhikgojghnnfjan
