### ISSUE TITLE
升级3.01后 不能发送了 

### ISSUE THREAD

**Issue by Cyiming** [scoful/cloudSkyMonster#34]
![image](https://github.com/scoful/cloudSkyMonster/assets/45073586/0abe2cfb-41b6-4884-8c00-aba8c1a04613)

和onetab情况一样 怀疑是低版本内核问题 

![image](https://github.com/scoful/cloudSkyMonster/assets/45073586/e9d94ef9-2616-44c2-9388-538da05c7e19)

我尝试了降级 但是不让降级 现在插件也不敢删 被onetab弄怕了

**Comment by scoful** [comment]
可以先把你的数据导出，其他功能-导出，复制出来就行了

**Comment by scoful** [comment]
@Cyiming 你是什么浏览器啊？

**Comment by scoful** [comment]
或者试试快捷键，单个的话是alt+q,全部的话是Ctrl+q，或者网页上右键，能发送单个，看看是功能上的问题还是action的问题

**Comment by Cyiming** [comment]
> 或者试试快捷键，单个的话是alt+q,全部的话是Ctrl+q，或者网页上右键，能发送单个，看看是功能上的问题还是action的问题

快捷键可以用 我是360极速X

**Comment by scoful** [comment]
那功能是正常的，建议使用原装Chrome，体验原滋原味的功能
