### ISSUE TITLE
之前谷歌把crx装的插件自动删除了，可以问下还可以找回保存的网址吗？

### ISSUE THREAD

**Issue by RedBagel** [scoful/cloudSkyMonster#37]
之前谷歌把crx装的插件自动删除了，可以问下还可以找回吗？
比如本地存储在哪个位置，以及存储文件怎么打开
虽然那些网址不是很重要，但是如果能找回的话还是想找下。
非常感谢！

**Comment by scoful** [comment]
1. 理论上，如果没换电脑，没重装系统，重新安装这个插件，数据应该自动恢复，如果没有，那就是没了；
2. 本地存储是调用的chrome自带的api存储的，我也没搞清楚它加密到哪里了；
3. 假如之前，你开启过github或者gitee同步的话，配置一下token，就可以重新恢复历史数据；

**Comment by RedBagel** [comment]
好的，那应该是没了，比较久了，那会好像还没有同步功能。
感谢解答！
