### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by BSDxxxx** [scoful/cloudSkyMonster#4]
工具和标签页功能分开展示，右击插件图标显示标签页相关功能，类似：

![image](https://user-images.githubusercontent.com/59258592/74735731-3e291400-528c-11ea-9eaa-dcab666d23ec.png)

**Comment by scoful** [comment]
@BSDxxxx 已实现，用最新版v2.0.1试试，还有那个同步问题，刚开始，第一次进入后台弹窗要输入的是gitee的token，然后去gist功能里面，那四个功能，点了后弹窗，是需要先输入“确定”这2个字，不包括双引号，用于冷静一下，免得不小心点到了就直接覆盖掉了，点完后，如果没有token，才需要再次输入token的。试试。

**Comment by BSDxxxx** [comment]
@scoful 原来如此，第二次弹窗我没细看，以为点了确认就好了，现在可以同步了
