### ISSUE TITLE
manifest.json 有个错误

### ISSUE THREAD

**Issue by Shea11012** [scoful/cloudSkyMonster#40]
manifest.json 中 `js/contentScript.js` 与js文件夹内的名字没有对应导致无法安装

**Comment by scoful** [comment]
@Shea11012 是哪个浏览器这么牛逼，这样都能检查出来，chrome和edge都没事

**Comment by Shea11012** [comment]
> @Shea11012 是哪个浏览器这么牛逼，这样都能检查出来，chrome和edge都没事

应该是操作系统对文件大小写敏感的原因，我是Arch Linux用的edge

**Comment by scoful** [comment]
我上架了的，试试
https://microsoftedge.microsoft.com/addons/detail/cloudskymonster/hfinincbgekmplkkhnpaodhconghkboh

**Comment by scoful** [comment]
哦对了，edge审核太慢了，不是最新版

**Comment by Shea11012** [comment]
在chrome中尝试安装还是不行

**Comment by scoful** [comment]
@Shea11012 已更新源代码，chrome商店预计明天，edge商店预计7个工作日后

**Comment by scoful** [comment]
谷歌疯了？现在审核那么快，已经通过了hh
