### ISSUE TITLE
拖拽标签(组)开关打开后再关掉，会打开另一个

### ISSUE THREAD

**Issue by kytrun** [scoful/cloudSkyMonster#41]
感谢开源，很好用

![image](https://github.com/scoful/cloudSkyMonster/assets/32519285/5cb6e95a-8636-4082-b7f3-5cf8e87944c4)

另外，这个字好像不对 :)

**Comment by scoful** [comment]
1. 组和单个是互斥关系，所以开了一个就会关另一个，hh
2. 拖拽和拖曳，都可以表达吧，hh
