### ISSUE TITLE
问题: gist的token没有同步

### ISSUE THREAD

**Issue by capsiamese** [scoful/cloudSkyMonster#42]
我有两台电脑，一台从chrome商店下载了拓展，填写了gist同步， 然后在另一台电脑上再下载扩展，这个时候gist的token没有同步。

两台电脑的chrome登陆的相同账号。

**Comment by scoful** [comment]
@capsiamese 那个token安全起见，我没有上传给谷歌的，是存在本地的，另一个电脑也手动配置一下token就可以拉取数据了，相当于git的push和pull

**Comment by capsiamese** [comment]
只填了github的token并且开启了自动同步并保存了，但是实际上并没有自动同步。看日志只有同步到gitee的。

**Comment by scoful** [comment]
是的，设计的有2个同步
1个是基于增删改的基础上，立马触发同步gitee，没加上github是考虑网络和速度问题，求快；
1个是每隔XX时间就同步github(90min)和gitee(70min)，假如2个都配置了token的话，求稳；

**Comment by capsiamese** [comment]
如果只配置了github的是不会同步的吗？90分钟也没有同步github的。这个时间太久了，扩展的service worker不是一直可用的。

**Comment by scoful** [comment]
- 会同步的，当初我设计的过于复杂了，还根据浏览器和系统的闲时或忙时做判断，累加90min，观察一段时间看看，如果还不同步就真的有问题了。
- 那你觉得多少时间比较合适？

**Comment by capsiamese** [comment]
最好多加点选项， 可以自定义。
