### ISSUE TITLE
有时候右键扩展图标显示不出发送到标签页的功能

### ISSUE THREAD

**Issue by sjhsbhqf** [scoful/cloudSkyMonster#43]
有时候右键扩展图标显示不出发送到标签页的功能，如下图所示

![image](https://github.com/scoful/cloudSkyMonster/assets/41407099/dfcbf8a9-bca9-49a4-a4fb-b3c1d77661a7)

我重启浏览器后，或者禁用扩展再启用，还是显示不全右键菜单。

**Comment by sjhsbhqf** [comment]
只有重装扩展才能解决。

**Comment by scoful** [comment]
请问是什么系统平台和什么浏览器？

**Comment by sjhsbhqf** [comment]
> 请问是什么系统平台和什么浏览器？

win11    22H2

Chrome 120.0.6099.130（正式版本） （64 位）

**Comment by scoful** [comment]
无法复现，能否提供更详细的步骤

**Comment by sjhsbhqf** [comment]
> 无法复现，能否提供更详细的步骤

浏览器用好长一段时间后才会出现这个BUG，我也不能说复现就复现。不好意思哈

**Comment by scoful** [comment]
哦哦，那我先关了issue，后续有复现步骤麻烦再开issue

**Comment by sjhsbhqf** [comment]
> 哦哦，那我先关了issue，后续有复现步骤麻烦再开issue

好的
