### ISSUE TITLE
功能建议：配置里设置了打开标签并将其从标签列表中删除后，锁定标签组后点击标签，标签打开后被删除，希望锁定的优先级更高

### ISSUE THREAD

**Issue by BestQwerty** [scoful/cloudSkyMonster#44]
![image](https://github.com/scoful/cloudSkyMonster/assets/44726454/276fcb57-4574-47bc-9a20-b7616403e0c0)
不锁定的话，可以点击标签后将其从列表删除，但是锁定后不希望被删除

**Comment by scoful** [comment]
已实现，chrome和edge在陆续审核上架

**Comment by BestQwerty** [comment]
> 已实现，chrome和edge在陆续审核上架

谢谢
