### ISSUE TITLE
【BUG】3.0.4最新版本，无法使用快捷键发送标签

### ISSUE THREAD

**Issue by BestQwerty** [scoful/cloudSkyMonster#45]
测试了两台电脑，都出现相同情况，快捷键无法使用

**Comment by scoful** [comment]
请问是什么系统什么浏览器？

**Comment by BestQwerty** [comment]
> 请问是什么系统什么浏览器？

一个是win10，一个是Win11，使用的浏览器都是百分浏览器（基于谷歌内核）

**Comment by scoful** [comment]
上一个版本的可以？

**Comment by BestQwerty** [comment]
> 上一个版本的可以？

未尝试 从3.0.2直接升级到3.0.4版本的

**Comment by scoful** [comment]
![image](https://github.com/scoful/cloudSkyMonster/assets/12808733/620f7f92-90dd-4491-ae5c-dd6a39767993)
![image](https://github.com/scoful/cloudSkyMonster/assets/12808733/15a0ef9e-1404-4e5d-9b81-19b35f5898bf)
试了下你这个浏览器，可以使用快捷键哦，可以手动点击左上角的三条横杆，点进去有所有插件的快捷键列表，看看是否生效或者被其他插件覆盖了。

**Comment by BestQwerty** [comment]
1

> ![image](https://private-user-images.githubusercontent.com/12808733/294090934-620f7f92-90dd-4491-ae5c-dd6a39767993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzc5OTEsIm5iZiI6MTcwNDM3NzY5MSwicGF0aCI6Ii8xMjgwODczMy8yOTQwOTA5MzQtNjIwZjdmOTItOTBkZC00NDkxLWFlNWMtZGQ2YTM5NzY3OTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNTJjNWZmMDVmYzNmYzEzNWM4ZWQzYTc1MjIzY2Y2ZWVlNzRkZWFjZGRjNmE5YTQyNjFkMDhiNjQ0NWY0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t0o-yL7mVHvYXm6Y477TnqWFpFZ4VbCn5gyJSye8mc8) ![image](https://private-user-images.githubusercontent.com/12808733/294091019-15a0ef9e-1404-4e5d-9b81-19b35f5898bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzc5OTEsIm5iZiI6MTcwNDM3NzY5MSwicGF0aCI6Ii8xMjgwODczMy8yOTQwOTEwMTktMTVhMGVmOWUtMTQwNC00ZTVkLTliODEtMTliMzVmNTg5OGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE0MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNjY3N2QyY2RkNjEwMzQ4ZTc3YWFjNzc3ZTcyNGNlMmZlYWE0OWZmZTE5NDlhYzk1MzMyMzI1MmI0YmQ0ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RuvIt4CRCrCSw5sEpHrOdy0M8NkQqbe7gI5cHrGQhws) 试了下你这个浏览器，可以使用快捷键哦，可以手动点击左上角的三条横杆，点进去有所有插件的快捷键列表，看看是否生效或者被其他插件覆盖了。

谢谢解决了，不知道为什么导入3.0.4版本快捷键自动清空了，3.0.2正常，重新手动设置了
