### ISSUE TITLE
显示BUG-已使用

### ISSUE THREAD

**Issue by sjhsbhqf** [scoful/cloudSkyMonster#47]
**环境信息**
- 操作系统：win11
- 浏览器名称：chrome 
- 浏览器版本：120.0.6099.131
- 插件版本号：3.0.5
- 是商店安装版还是代码安装版：商店安装版

**描述遇到的情况**
在标签页管理界面，容量显示异常

![image](https://github.com/scoful/N-Tab/assets/41407099/912ebb3d-0548-49f0-be3f-654025a092c9)

**复现步骤（如果有的话，无留空或删掉）**
按照以下步骤复现错误：
1. 前往 '后台管理页'
2. 看到已经占用了 7.21mb，点击后显示yishiyong已使用7.21%

![image](https://github.com/scoful/N-Tab/assets/41407099/f541467e-fdc9-46fa-b51c-740ed33792ca)

---

**Comment by scoful** [comment]
请问你这个7.21mb是怎么弄出来的，757总数的记录，不可能占用了这么多的，尝试了1w多条，才占用了2mb多一点
![image](https://github.com/scoful/N-Tab/assets/12808733/d961bbca-d0fd-4ef8-bd41-610a77e52e11)

**Comment by sjhsbhqf** [comment]
> 请问你这个7.21mb是怎么弄出来的，757总数的记录，不可能占用了这么多的，尝试了1w多条，才占用了2mb多一点 ![image](https://private-user-images.githubusercontent.com/12808733/295507277-d961bbca-d0fd-4ef8-bd41-610a77e52e11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzczMDUsIm5iZiI6MTcwNDg3NzAwNSwicGF0aCI6Ii8xMjgwODczMy8yOTU1MDcyNzctZDk2MWJiY2EtZDBmZC00ZWY4LWJkNDEtNjEwYTc3ZTUyZTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA4NTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxOTY2ODVkM2VmZGFiNjFjMmU4YjAwNjhlZDhmZTdlZjcyNDRmMGEyYzBhZDQxZTZlN2NiMTY1ZTVjYjkyZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4tlJH3mNQEaaW9FOXJKQQaGBvMqaVBc-tUcaAKOz9UA)

我个人觉得应该是显示的问题，实际应该是没占这么多吧？因为我点击上面的时候，会转而显示占用同样数字的百分比，这个百分比不符合那个MB显示的数字比例。你觉得呢？

另外你需要什么测试数据请随时询问我，我愿意提供以帮助这个插件越加完善。

**Comment by scoful** [comment]
- 那个百分百切换的确是我写错了，应该不关这个事。
- 你方便把你的数据导出一份给我吗？路径：其他功能-导出，然后复制到个文本文件里，发邮件给我这边试试导入，看看总量对不对。邮箱地址：[1269717999@qq.com](mailto:1269717999@qq.com)
- 我刚又去翻了官网api，我现在有点怀疑这个总量是所有插件共享的，但是官网api又没说，可能得发邮件给谷歌问问看

**Comment by sjhsbhqf** [comment]
> * 那个百分百切换的确是我写错了，应该不关这个事。
> * 你方便把你的数据导出一份给我吗？路径：其他功能-导出，然后复制到个文本文件里，发邮件给我这边试试导入，看看总量对不对。邮箱地址：[1269717999@qq.com](mailto:1269717999@qq.com)
> * 我刚又去翻了官网api，我现在有点怀疑这个总量是所有插件共享的，但是官网api又没说，可能得发邮件给谷歌问问看

好的。非常奇怪的是，我又往里面添加了一项，发现容量反而减小了。

![image](https://github.com/scoful/N-Tab/assets/41407099/469bcc30-4a9d-4232-b22c-b2a37137de12)

**Comment by sjhsbhqf** [comment]
刚刚已发送邮件。

另外，我的这个GitHub或Gitee的gist只在这个插件上用

**Comment by sjhsbhqf** [comment]
好了刚刚跟开发者沟通，已经通过卸载扩展程序和重新配置，重新拉取标签数据得到解决。

![image](https://github.com/scoful/N-Tab/assets/41407099/a8b83df9-2e85-49f7-a521-1a9a2beb32ed)
