### ISSUE TITLE
重大bug

### ISSUE THREAD

**Issue by BSDxxxx** [scoful/cloudSkyMonster#5]
gitee和github假同步导致数据无法恢复：

重置系统前确定已经点击同步，api状态都正常，已使用空间不为0。

重置系统后，输入之前的gitee api token，api显示正常，但已用空间为0，同步内容为空。

使用的版本是最新源码。

**Comment by scoful** [comment]
@BSDxxxx 打开gitee，看看代码片段，里面有没有你最后一次的数据。这里面的更新逻辑都是覆盖更新的，比如本地push到远程，远程的就会被覆盖，远程pull到本地，本地就会被覆盖。默认开启的是gitee的，只要标签页有变化，就会自动push到gitee。
是不是觉得很复杂，我也觉得，打算阉割掉手动更新的功能，只剩下自动的好了。

**Comment by BSDxxxx** [comment]
@scoful 试着同步了几次，gitee的代码片段什么都没有。

**Comment by scoful** [comment]
@BSDxxxx gitee的代码片段可以看历史记录的，右上角点一下看看。方便的话，你加我微信，可能交流方便一点

**Comment by BSDxxxx** [comment]
@scoful 好的，我微信号：yaohunzhanyue

**Comment by yijiang2012** [comment]
支持一下，今天意识到chrome占用很多内存，所以找到了onetab，但是看到大家在各个网站上的评论家知道onetab也有缺点，且作者失联。然后看到本插件作者的回帖广告就找到了这里，希望能有更多人支持这款好插件

**Comment by yijiang2012** [comment]
左键之后的显示菜单，建议把分割线下面所有标签内容放在最上面，分割线上面的包括二维码都放到下面。因为最常用最需要的是快速浏览和关闭标签菜单

**Comment by BSDxxxx** [comment]
> 左键之后的显示菜单，建议把分割线下面所有标签内容放在最上面，分割线上面的包括二维码都放到下面。因为最常用最需要的是快速浏览和关闭标签菜单

https://github.com/scoful/cloudSkyMonster/issues/4

**Comment by yijiang2012** [comment]
我收回刚才的建议，因为刚弄懂这个插件的好处，就是可以在第一个标签快速形成一个临时标签，替换并且收藏所有的标签，相当于是一个临时收藏夹。希望这个临时收藏夹能够保存在本地的一个指定文件夹里，突然停电或死机还可以找回来是最实用的。git的gist正常上网是打不开的吗?还好gitee的gist可以快速创建打开

**Comment by yijiang2012** [comment]
平时手动收藏每个喜欢的网页地址。所以，对于我来说，最实用最常用的一件发送所有标签的功能，快速的把所有标签都收归到一个临时标签，这个太好用，关键是节省内存，太感谢了

**Comment by BSDxxxx** [comment]
@yijiang2012 请问你同步后的gitee代码片段有显示内容吗？

**Comment by 1160300929** [comment]
妈的 onetab真是弟弟插件，我特么的重要的标签页全丢了

**Comment by BSDxxxx** [comment]
> 妈的 onetab真是弟弟插件，我特么的重要的标签页全丢了

better one tab也是，明明同步成功了，结果还是丢失

**Comment by scoful** [comment]
@BSDxxxx 帅哥加你了，搞了个新版本了

**Comment by yaohunzhanyue** [comment]
@scoful 这么久没动静，还以为你弃坑了啊，没事就好。话说这条issue怎么没有close和delete按钮了？

**Comment by BSDxxxx** [comment]
@scoful 收到！
