### ISSUE TITLE
小白问题：那个token的expiration时间应该怎么设置？谢谢

### ISSUE THREAD

**Issue by lin-du** [scoful/cloudSkyMonster#50]

**Comment by lin-du** [comment]
另外还想请问一下怎么看出来gitee上面有没有同步成功。还有为啥那个push to Gitee's list是个比较危险的操作需要confirm？是因为push to Gitee's list会把现在浏览器已经打开的tab推过去吗，还是会把存在N-tab里的那些标签同步过去？其实我还不太理解这个插件的逻辑。。。

**Comment by scoful** [comment]
@lin-du 
- 看有没有同步成功有2种方法，1个是看日志，路径：其他功能-查看日志，1个就是去gitee看gist有没有同步过去。
- 手动点的那4个，要confirm是因为会覆盖掉。
- 插件会把存在N-tab里的那些标签同步过去，浏览器打开那些不会同步。
- token的expiration时间是github和gitee控制的，我记得是可以选永久不过期的。如果过期就只能重新生成然后填到设置里。
- 插件的逻辑你是哪块不理解？如果没有同步的需求，完全可以不管它，就正常使用就ok了。

**Comment by scoful** [comment]
@lin-du 可以简单的认为，oneTab的基础上，增加了一些个性化功能

**Comment by scoful** [comment]
如无问题，我先关闭issue了，有问题请再打开
