### ISSUE TITLE
记录百分比的bug

### ISSUE THREAD

**Issue by feeltens** [scoful/cloudSkyMonster#51]
**环境信息**
- 操作系统：macOS Sonama 14.2.1
- 浏览器名称：Vivaldi
- 浏览器版本：6.5.3206.53
- 插件版本号：3.0.5
- 是商店安装版

**预期行为**
如下图：6MB / 10 MB 的占比应该是 60%

**截图**
<img width="862" alt="image" src="https://github.com/scoful/N-Tab/assets/20438803/c9ac6c48-b1ef-4b5c-9b21-6c27a78ff0d6">

<img width="818" alt="image" src="https://github.com/scoful/N-Tab/assets/20438803/ffe45b3d-838c-404d-9764-5ec96b5650cd">

---

**Comment by scoful** [comment]
已修复，已上传代码，chrome商店已发布
