### ISSUE TITLE
功能建议：锁定后点击打开整组后不要自动删除标签组

### ISSUE THREAD

**Issue by BestQwerty** [scoful/cloudSkyMonster#54]
**环境信息**
- 操作系统：win11
- 浏览器名称：Cent Browser
- 浏览器版本：5.0.1002.354
- 插件版本号：3.0.5
- 是商店安装版还是代码安装版：代码安装版

**描述遇到的情况**
[锁定后打开整组后还是自动删除标签组。还是跟[上次提的issue](https://github.com/scoful/N-Tab/issues/44)一样，希望锁定优先级更高。
![image](https://github.com/scoful/N-Tab/assets/44726454/91e80d41-6dfa-4703-9d09-6b57cc429c0d)
![image](https://github.com/scoful/N-Tab/assets/44726454/a4a8bcc1-1239-4bc8-bbdb-bdfd1cce422e)

**Comment by scoful** [comment]
已实现，已上传代码，chrome商店已发布
