### ISSUE TITLE
功能建议: Gist同步, 是否可以加密/不对外公开

### ISSUE THREAD

**Issue by WilliamZY** [scoful/cloudSkyMonster#60]
**环境信息**
- 操作系统：Win11
- 浏览器名称：Microsoft Edge
- 浏览器版本：121.0.2277.98 
- 插件版本号：3.1.0
- 是商店安装版还是代码安装版：商店

**描述遇到的情况**
目前Gist创建的都是公开的gist, 因为其中有一些NSFW的内容, 所以觉得是否能做成默认私有gist, 对隐私也能做一些保护

或者 对上传的**部分内容**作加密, 可以选择非对称加密, 拉取的时候进行解密.

**Comment by scoful** [comment]
N-Tab创建的gist都是私有的哦，您那边是public的？

**Comment by WilliamZY** [comment]
的确是私有的 理解错了不好意思 主要以为私有的不能通过链接直接访问

另外 gist的标题还是 myCloudSkyMonster, 没改成新名字
