### ISSUE TITLE
老哥新年好. 反馈一个gitee可能的同步问题(存疑)

### ISSUE THREAD

**Issue by yukminnie** [scoful/cloudSkyMonster#63]
## 祝老哥新年身体健康 事业节节升 

> 环境

操作系统: windows11 macos10.14 macos10.15 macos11.5.4

浏览器: chrome最新

n-tab版本: 最新(商店版和手动安装都已尝试过)

> 描述: 

软件我大概用了一周了, 目前的问题就是gitee在刚配置好的时候, 自动同步是正常的, logs和远程gist检查, 都有内容输出.

大概就是电脑放置一段时间, 通常来说是过了一夜后, 第二天再次打开, gitee就没法自动同步了, 但是手动pull和push是正常的.

> 尝试过的手段:

- 更换商店版和手动安装板
- 开关网络代理
- 甚至升级了macos版本(10.14只能支持到chrome116, 升级到10.15安装了chrome121情况依旧)
- pc同上

> 问题解决:

最后怎么解决呢, 我手动安装了第二个大版本的最后一个, 也就是3.0之前那个, 现在已经使用了两天, 目前一切正常.

**Comment by NJYZ-96** [comment]
遇到同样问题，不仅仅是gitee，github也会在一段时间后不再自动同步，但手动是没问题的；

@yukminnie 老哥为啥把议题关闭了，后面的人就很难看到了
