### ISSUE TITLE
希望像OneTab一样有保留分组名和还原功能，同时集成一下标签页命名功能

### ISSUE THREAD

**Issue by insovo** [scoful/cloudSkyMonster#92]
在分组状态下：
- OneTab点击扩展图标就可以发送标签页，并且是仅当前分组（不会影响到其它分组），这点比较好；
- N-Tab发送所有标签页会将当前所有打开的标签页全部收纳，并且不会保留浏览器分组信息；
![image](https://github.com/user-attachments/assets/6428c369-4cb0-4842-a9ed-1c8272a7ecbf)
要修改浏览器标签页名称需要安装额外的插件，如果能集成就好了
![image](https://github.com/user-attachments/assets/71f55c15-6496-47fb-9286-0d8077d849c6)

**Comment by sjhsbhqf** [comment]
你为啥关掉这个issue，好像现在没有办法保留分组信息
